### ISSUE TITLE
Catch use of unset names when running Check

### ISSUE THREAD

**Issue by amoeba** [NCEAS/mdqengine#13]
I can produce a NPE when I run a badly-written check.

With the suite:

```{xml}
<?xml version="1.0" encoding="UTF-8"?>
<suite>
    <name>test suite</name>
    <check>
        <name>check A</name>
        <level>ERROR</level>
        <expected>true</expected>
        <environment>r</environment>
        <code><![CDATA[
          x
      ]]></code>
    </check>
</suite>
```

I run and get:

```{sh}
$ pwd
/Users/mecum/src/mdqengine
mecum at mecum in ~/src/mdqengine
$ mvn exec:java -Dexec.mainClass="edu.ucsb.nceas.mdqengine.MDQEngine" -Dexec.args="$SUITE $DOC"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building mdqengine 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ mdqengine ---
 INFO [edu.ucsb.nceas.mdqengine.MDQEngine.main()] (XMLDialect.java:194) - No dialects have been specified for check, assuming it is valid for this document
java.lang.NullPointerException
	at edu.ucsb.nceas.mdqengine.processor.XMLDialect.runCheck(XMLDialect.java:78)
	at edu.ucsb.nceas.mdqengine.MDQEngine.runSuite(MDQEngine.java:107)
	at edu.ucsb.nceas.mdqengine.MDQEngine.main(MDQEngine.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.076 s
[INFO] Finished at: 2016-07-21T16:21:44-08:00
[INFO] Final Memory: 21M/265M
[INFO] ------------------------------------------------------------------------
mecum at mecum in ~/src/mdqengine
```

I also get an NPE if I just have no <selector> and an empty <code> element:

```{xml}
<?xml version="1.0" encoding="UTF-8"?>
<suite>
    <name>test suite</name>
    <check>
      <name>check A</name>
      <level>ERROR</level>
      <expected>true</expected>
      <environment>r</environment>
      <code><![CDATA[
      ]]></code>
    </check>
</suite>
```

I think the Result should contain enough information to tell the person reading it what happened. Does that seem reasonable?

**Comment by leinfelder** [comment]
added check for missing selectors before trying to set variables in the environment
